import type { CmsPage } from "@/lib/cms/types";

/** Default page set shipped with the CMS (static + dynamic templates). */
export const SEED_PAGES: CmsPage[] = [
  {
    id: "pg_home",
    title: "Home",
    slug: "",
    kind: "static",
    status: "publish",
    parentId: null,
    template: "Landing page",
    content: "Welcome to Techtrick CMS. This is the front page of the site.",
    seoTitle: "Techtrick CMS — Home",
    seoDescription: "The open-source admin and site builder by Techtrick Technologies.",
    author: "admin",
    createdAt: "2026-06-01T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
  },
  {
    id: "pg_about",
    title: "About",
    slug: "about",
    kind: "static",
    status: "publish",
    parentId: null,
    template: "Default template",
    content: "Who we are and what we build.",
    seoTitle: "About — Techtrick CMS",
    seoDescription: "About Techtrick Technologies.",
    author: "admin",
    createdAt: "2026-06-03T10:00:00Z",
    updatedAt: "2026-07-14T10:00:00Z",
  },
  {
    id: "pg_contact",
    title: "Contact",
    slug: "contact",
    kind: "static",
    status: "publish",
    parentId: null,
    template: "Sidebar right",
    content: "Reach the team at hello@techtrick.com.bd.",
    seoTitle: "Contact — Techtrick CMS",
    seoDescription: "Contact Techtrick Technologies.",
    author: "admin",
    createdAt: "2026-06-09T10:00:00Z",
    updatedAt: "2026-07-02T10:00:00Z",
  },
  {
    id: "pg_privacy",
    title: "Privacy Policy",
    slug: "privacy-policy",
    kind: "static",
    status: "draft",
    parentId: null,
    template: "Default template",
    content: "Draft privacy policy.",
    seoTitle: "",
    seoDescription: "",
    author: "admin",
    createdAt: "2026-06-11T10:00:00Z",
    updatedAt: "2026-06-11T10:00:00Z",
  },
  {
    id: "pg_blog",
    title: "Blog",
    slug: "blog",
    kind: "dynamic",
    status: "publish",
    parentId: null,
    template: "Full width",
    content: "",
    seoTitle: "Blog — Techtrick CMS",
    seoDescription: "Latest posts.",
    author: "admin",
    source: "post-archive",
    perPage: 10,
    createdAt: "2026-06-15T10:00:00Z",
    updatedAt: "2026-08-04T10:00:00Z",
  },
  {
    id: "pg_category",
    title: "Category archive",
    slug: "category/:slug",
    kind: "dynamic",
    status: "publish",
    parentId: null,
    template: "Sidebar left",
    content: "",
    seoTitle: "",
    seoDescription: "",
    author: "admin",
    source: "category-archive",
    perPage: 12,
    createdAt: "2026-06-15T10:05:00Z",
    updatedAt: "2026-07-28T10:00:00Z",
  },
  {
    id: "pg_search",
    title: "Search results",
    slug: "search",
    kind: "dynamic",
    status: "publish",
    parentId: null,
    template: "Full width",
    content: "",
    seoTitle: "",
    seoDescription: "",
    author: "admin",
    source: "search-results",
    perPage: 20,
    createdAt: "2026-06-16T10:00:00Z",
    updatedAt: "2026-07-20T10:00:00Z",
  },
  {
    id: "pg_single",
    title: "Single post",
    slug: "post/:slug",
    kind: "dynamic",
    status: "publish",
    parentId: null,
    template: "Sidebar right",
    content: "",
    seoTitle: "",
    seoDescription: "",
    author: "admin",
    source: "single-post",
    createdAt: "2026-06-16T10:10:00Z",
    updatedAt: "2026-08-06T10:00:00Z",
  },
];
