/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/site'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WpAdminIndexRouteImport } from './routes/wp-admin.index'
import { Route as SiteIndexRouteImport } from './routes/site.index'
import { Route as WpAdminSplatRouteImport } from './routes/wp-admin.$'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminPostsRouteImport } from './routes/_admin/admin.posts'
import { Route as AdminAdminPagesRouteImport } from './routes/_admin/admin.pages'
import { Route as AdminAdminCommentsRouteImport } from './routes/_admin/admin.comments'
import { Route as AdminAdminAppearanceRouteImport } from './routes/_admin/admin.appearance'
import { Route as AdminAdminSecurityIndexRouteImport } from './routes/_admin/admin.security.index'
import { Route as AdminAdminPagesIndexRouteImport } from './routes/_admin/admin.pages.index'
import { Route as AdminAdminToolsPerformanceRouteImport } from './routes/_admin/admin.tools.performance'
import { Route as AdminAdminSecurityCloudflareRouteImport } from './routes/_admin/admin.security.cloudflare'
import { Route as AdminAdminPagesNewRouteImport } from './routes/_admin/admin.pages.new'
import { Route as AdminAdminPagesIdRouteImport } from './routes/_admin/admin.pages.$id'

const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WpAdminIndexRoute = WpAdminIndexRouteImport.update({
  id: '/wp-admin/',
  path: '/wp-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const WpAdminSplatRoute = WpAdminSplatRouteImport.update({
  id: '/wp-admin/$',
  path: '/wp-admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminPostsRoute = AdminAdminPostsRouteImport.update({
  id: '/admin/posts',
  path: '/admin/posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminPagesRoute = AdminAdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminCommentsRoute = AdminAdminCommentsRouteImport.update({
  id: '/admin/comments',
  path: '/admin/comments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminAppearanceRoute = AdminAdminAppearanceRouteImport.update({
  id: '/admin/appearance',
  path: '/admin/appearance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminSecurityIndexRoute = AdminAdminSecurityIndexRouteImport.update({
  id: '/admin/security/',
  path: '/admin/security/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminPagesIndexRoute = AdminAdminPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminPagesRoute,
} as any)
const AdminAdminToolsPerformanceRoute =
  AdminAdminToolsPerformanceRouteImport.update({
    id: '/admin/tools/performance',
    path: '/admin/tools/performance',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAdminSecurityCloudflareRoute =
  AdminAdminSecurityCloudflareRouteImport.update({
    id: '/admin/security/cloudflare',
    path: '/admin/security/cloudflare',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAdminPagesNewRoute = AdminAdminPagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminAdminPagesRoute,
} as any)
const AdminAdminPagesIdRoute = AdminAdminPagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminPagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/site': typeof SiteRouteWithChildren
  '/site/$slug': typeof SiteSlugRoute
  '/wp-admin/$': typeof WpAdminSplatRoute
  '/site/': typeof SiteIndexRoute
  '/wp-admin/': typeof WpAdminIndexRoute
  '/admin/appearance': typeof AdminAdminAppearanceRoute
  '/admin/comments': typeof AdminAdminCommentsRoute
  '/admin/pages': typeof AdminAdminPagesRouteWithChildren
  '/admin/posts': typeof AdminAdminPostsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/pages/$id': typeof AdminAdminPagesIdRoute
  '/admin/pages/new': typeof AdminAdminPagesNewRoute
  '/admin/security/cloudflare': typeof AdminAdminSecurityCloudflareRoute
  '/admin/tools/performance': typeof AdminAdminToolsPerformanceRoute
  '/admin/pages/': typeof AdminAdminPagesIndexRoute
  '/admin/security/': typeof AdminAdminSecurityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/site/$slug': typeof SiteSlugRoute
  '/wp-admin/$': typeof WpAdminSplatRoute
  '/site': typeof SiteIndexRoute
  '/wp-admin': typeof WpAdminIndexRoute
  '/admin/appearance': typeof AdminAdminAppearanceRoute
  '/admin/comments': typeof AdminAdminCommentsRoute
  '/admin/posts': typeof AdminAdminPostsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/pages/$id': typeof AdminAdminPagesIdRoute
  '/admin/pages/new': typeof AdminAdminPagesNewRoute
  '/admin/security/cloudflare': typeof AdminAdminSecurityCloudflareRoute
  '/admin/tools/performance': typeof AdminAdminToolsPerformanceRoute
  '/admin/pages': typeof AdminAdminPagesIndexRoute
  '/admin/security': typeof AdminAdminSecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/site': typeof SiteRouteWithChildren
  '/site/$slug': typeof SiteSlugRoute
  '/wp-admin/$': typeof WpAdminSplatRoute
  '/site/': typeof SiteIndexRoute
  '/wp-admin/': typeof WpAdminIndexRoute
  '/_admin/admin/appearance': typeof AdminAdminAppearanceRoute
  '/_admin/admin/comments': typeof AdminAdminCommentsRoute
  '/_admin/admin/pages': typeof AdminAdminPagesRouteWithChildren
  '/_admin/admin/posts': typeof AdminAdminPostsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/pages/$id': typeof AdminAdminPagesIdRoute
  '/_admin/admin/pages/new': typeof AdminAdminPagesNewRoute
  '/_admin/admin/security/cloudflare': typeof AdminAdminSecurityCloudflareRoute
  '/_admin/admin/tools/performance': typeof AdminAdminToolsPerformanceRoute
  '/_admin/admin/pages/': typeof AdminAdminPagesIndexRoute
  '/_admin/admin/security/': typeof AdminAdminSecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/site'
    | '/site/$slug'
    | '/wp-admin/$'
    | '/site/'
    | '/wp-admin/'
    | '/admin/appearance'
    | '/admin/comments'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/'
    | '/admin/pages/$id'
    | '/admin/pages/new'
    | '/admin/security/cloudflare'
    | '/admin/tools/performance'
    | '/admin/pages/'
    | '/admin/security/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/site/$slug'
    | '/wp-admin/$'
    | '/site'
    | '/wp-admin'
    | '/admin/appearance'
    | '/admin/comments'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin'
    | '/admin/pages/$id'
    | '/admin/pages/new'
    | '/admin/security/cloudflare'
    | '/admin/tools/performance'
    | '/admin/pages'
    | '/admin/security'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/site'
    | '/site/$slug'
    | '/wp-admin/$'
    | '/site/'
    | '/wp-admin/'
    | '/_admin/admin/appearance'
    | '/_admin/admin/comments'
    | '/_admin/admin/pages'
    | '/_admin/admin/posts'
    | '/_admin/admin/settings'
    | '/_admin/admin/'
    | '/_admin/admin/pages/$id'
    | '/_admin/admin/pages/new'
    | '/_admin/admin/security/cloudflare'
    | '/_admin/admin/tools/performance'
    | '/_admin/admin/pages/'
    | '/_admin/admin/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  WpAdminSplatRoute: typeof WpAdminSplatRoute
  WpAdminIndexRoute: typeof WpAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wp-admin/': {
      id: '/wp-admin/'
      path: '/wp-admin'
      fullPath: '/wp-admin/'
      preLoaderRoute: typeof WpAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/': {
      id: '/site/'
      path: '/'
      fullPath: '/site/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/wp-admin/$': {
      id: '/wp-admin/$'
      path: '/wp-admin/$'
      fullPath: '/wp-admin/$'
      preLoaderRoute: typeof WpAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/posts': {
      id: '/_admin/admin/posts'
      path: '/admin/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminAdminPostsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/pages': {
      id: '/_admin/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminAdminPagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/comments': {
      id: '/_admin/admin/comments'
      path: '/admin/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminAdminCommentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/appearance': {
      id: '/_admin/admin/appearance'
      path: '/admin/appearance'
      fullPath: '/admin/appearance'
      preLoaderRoute: typeof AdminAdminAppearanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/security/': {
      id: '/_admin/admin/security/'
      path: '/admin/security'
      fullPath: '/admin/security/'
      preLoaderRoute: typeof AdminAdminSecurityIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/pages/': {
      id: '/_admin/admin/pages/'
      path: '/'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminAdminPagesIndexRouteImport
      parentRoute: typeof AdminAdminPagesRoute
    }
    '/_admin/admin/tools/performance': {
      id: '/_admin/admin/tools/performance'
      path: '/admin/tools/performance'
      fullPath: '/admin/tools/performance'
      preLoaderRoute: typeof AdminAdminToolsPerformanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/security/cloudflare': {
      id: '/_admin/admin/security/cloudflare'
      path: '/admin/security/cloudflare'
      fullPath: '/admin/security/cloudflare'
      preLoaderRoute: typeof AdminAdminSecurityCloudflareRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/pages/new': {
      id: '/_admin/admin/pages/new'
      path: '/new'
      fullPath: '/admin/pages/new'
      preLoaderRoute: typeof AdminAdminPagesNewRouteImport
      parentRoute: typeof AdminAdminPagesRoute
    }
    '/_admin/admin/pages/$id': {
      id: '/_admin/admin/pages/$id'
      path: '/$id'
      fullPath: '/admin/pages/$id'
      preLoaderRoute: typeof AdminAdminPagesIdRouteImport
      parentRoute: typeof AdminAdminPagesRoute
    }
  }
}

interface AdminAdminPagesRouteChildren {
  AdminAdminPagesIdRoute: typeof AdminAdminPagesIdRoute
  AdminAdminPagesNewRoute: typeof AdminAdminPagesNewRoute
  AdminAdminPagesIndexRoute: typeof AdminAdminPagesIndexRoute
}

const AdminAdminPagesRouteChildren: AdminAdminPagesRouteChildren = {
  AdminAdminPagesIdRoute: AdminAdminPagesIdRoute,
  AdminAdminPagesNewRoute: AdminAdminPagesNewRoute,
  AdminAdminPagesIndexRoute: AdminAdminPagesIndexRoute,
}

const AdminAdminPagesRouteWithChildren = AdminAdminPagesRoute._addFileChildren(
  AdminAdminPagesRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAdminAppearanceRoute: typeof AdminAdminAppearanceRoute
  AdminAdminCommentsRoute: typeof AdminAdminCommentsRoute
  AdminAdminPagesRoute: typeof AdminAdminPagesRouteWithChildren
  AdminAdminPostsRoute: typeof AdminAdminPostsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminSecurityCloudflareRoute: typeof AdminAdminSecurityCloudflareRoute
  AdminAdminToolsPerformanceRoute: typeof AdminAdminToolsPerformanceRoute
  AdminAdminSecurityIndexRoute: typeof AdminAdminSecurityIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminAppearanceRoute: AdminAdminAppearanceRoute,
  AdminAdminCommentsRoute: AdminAdminCommentsRoute,
  AdminAdminPagesRoute: AdminAdminPagesRouteWithChildren,
  AdminAdminPostsRoute: AdminAdminPostsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminSecurityCloudflareRoute: AdminAdminSecurityCloudflareRoute,
  AdminAdminToolsPerformanceRoute: AdminAdminToolsPerformanceRoute,
  AdminAdminSecurityIndexRoute: AdminAdminSecurityIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SiteRouteChildren {
  SiteSlugRoute: typeof SiteSlugRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteSlugRoute: SiteSlugRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  WpAdminSplatRoute: WpAdminSplatRoute,
  WpAdminIndexRoute: WpAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
