/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminPostsRouteImport } from './routes/_admin/admin.posts'
import { Route as AdminAdminPagesRouteImport } from './routes/_admin/admin.pages'
import { Route as AdminAdminCommentsRouteImport } from './routes/_admin/admin.comments'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminPostsRoute = AdminAdminPostsRouteImport.update({
  id: '/admin/posts',
  path: '/admin/posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminPagesRoute = AdminAdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminCommentsRoute = AdminAdminCommentsRouteImport.update({
  id: '/admin/comments',
  path: '/admin/comments',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/comments': typeof AdminAdminCommentsRoute
  '/admin/pages': typeof AdminAdminPagesRoute
  '/admin/posts': typeof AdminAdminPostsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/comments': typeof AdminAdminCommentsRoute
  '/admin/pages': typeof AdminAdminPagesRoute
  '/admin/posts': typeof AdminAdminPostsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_admin/admin/comments': typeof AdminAdminCommentsRoute
  '/_admin/admin/pages': typeof AdminAdminPagesRoute
  '/_admin/admin/posts': typeof AdminAdminPostsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/comments'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/comments'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_admin/admin/comments'
    | '/_admin/admin/pages'
    | '/_admin/admin/posts'
    | '/_admin/admin/settings'
    | '/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/posts': {
      id: '/_admin/admin/posts'
      path: '/admin/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminAdminPostsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/pages': {
      id: '/_admin/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminAdminPagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/comments': {
      id: '/_admin/admin/comments'
      path: '/admin/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminAdminCommentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminCommentsRoute: typeof AdminAdminCommentsRoute
  AdminAdminPagesRoute: typeof AdminAdminPagesRoute
  AdminAdminPostsRoute: typeof AdminAdminPostsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminCommentsRoute: AdminAdminCommentsRoute,
  AdminAdminPagesRoute: AdminAdminPagesRoute,
  AdminAdminPostsRoute: AdminAdminPostsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
