/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WpadminRouteRouteImport } from './routes/_wpadmin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WpadminWpAdminIndexRouteImport } from './routes/_wpadmin/wp-admin.index'
import { Route as WpadminWpAdminPostsRouteImport } from './routes/_wpadmin/wp-admin.posts'

const WpadminRouteRoute = WpadminRouteRouteImport.update({
  id: '/_wpadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WpadminWpAdminIndexRoute = WpadminWpAdminIndexRouteImport.update({
  id: '/wp-admin/',
  path: '/wp-admin/',
  getParentRoute: () => WpadminRouteRoute,
} as any)
const WpadminWpAdminPostsRoute = WpadminWpAdminPostsRouteImport.update({
  id: '/wp-admin/posts',
  path: '/wp-admin/posts',
  getParentRoute: () => WpadminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wp-admin/posts': typeof WpadminWpAdminPostsRoute
  '/wp-admin/': typeof WpadminWpAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wp-admin/posts': typeof WpadminWpAdminPostsRoute
  '/wp-admin': typeof WpadminWpAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_wpadmin': typeof WpadminRouteRouteWithChildren
  '/_wpadmin/wp-admin/posts': typeof WpadminWpAdminPostsRoute
  '/_wpadmin/wp-admin/': typeof WpadminWpAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wp-admin/posts' | '/wp-admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wp-admin/posts' | '/wp-admin'
  id:
    | '__root__'
    | '/'
    | '/_wpadmin'
    | '/_wpadmin/wp-admin/posts'
    | '/_wpadmin/wp-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WpadminRouteRoute: typeof WpadminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_wpadmin': {
      id: '/_wpadmin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WpadminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_wpadmin/wp-admin/': {
      id: '/_wpadmin/wp-admin/'
      path: '/wp-admin'
      fullPath: '/wp-admin/'
      preLoaderRoute: typeof WpadminWpAdminIndexRouteImport
      parentRoute: typeof WpadminRouteRoute
    }
    '/_wpadmin/wp-admin/posts': {
      id: '/_wpadmin/wp-admin/posts'
      path: '/wp-admin/posts'
      fullPath: '/wp-admin/posts'
      preLoaderRoute: typeof WpadminWpAdminPostsRouteImport
      parentRoute: typeof WpadminRouteRoute
    }
  }
}

interface WpadminRouteRouteChildren {
  WpadminWpAdminPostsRoute: typeof WpadminWpAdminPostsRoute
  WpadminWpAdminIndexRoute: typeof WpadminWpAdminIndexRoute
}

const WpadminRouteRouteChildren: WpadminRouteRouteChildren = {
  WpadminWpAdminPostsRoute: WpadminWpAdminPostsRoute,
  WpadminWpAdminIndexRoute: WpadminWpAdminIndexRoute,
}

const WpadminRouteRouteWithChildren = WpadminRouteRoute._addFileChildren(
  WpadminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WpadminRouteRoute: WpadminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
